"""Init DB

Revision ID: 9368a1d37507
Revises: 5b588fa4411f
Create Date: 2025-12-10 10:31:20.743201

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "9368a1d37507"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = "5b588fa4411f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
